=== api-evangelist/amazon/json-schema/pay-address-schema.json
{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "addressLine1": {
      "type": "string"
    },
    "addressLine2": {
      "type": "string"
    },
    "addressLine3": {
      "type": "string"
    },
    "city": {
      "type": "string"
    },
    "stateOrRegion": {
      "type": "string"
    },
    "postalCode": {
      "type": "string"
    },
    "countryCode": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Address",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon/refs/heads/main/json-schema/pay-address-schema.json",
  "description": "Address schema from Amazon Pay API"
}

=== api-evangelist/amazon/examples/pay-address-example.json
{
  "name": "Example Product",
  "addressLine1": "example-value",
  "addressLine2": "example-value",
  "addressLine3": "example-value",
  "city": "example-value",
  "stateOrRegion": "example-value",
  "postalCode": "example-value",
  "countryCode": "example-value",
  "phoneNumber": "example-value"
}
